2025-05-04 13:59:23.293016-03:00 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT * FROM CONTACT \000d\000a\000d\000aUpdate [*]'FAVORITO' = TRUE WHERE 'FAVORITO' = FALSE"; SQL statement:
SELECT * FROM CONTACT 

Update 'FAVORITO' = TRUE WHERE 'FAVORITO' = FALSE [42000-232]
2025-05-04 13:59:40.087748-03:00 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT * FROM CONTACT \000d\000a\000d\000aUpdate [*]FROM CONTACT 'FAVORITO' = TRUE WHERE 'FAVORITO' = FALSE"; SQL statement:
SELECT * FROM CONTACT 

Update FROM CONTACT 'FAVORITO' = TRUE WHERE 'FAVORITO' = FALSE [42000-232]
2025-05-04 13:59:45.977129-03:00 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT * FROM CONTACT \000d\000a\000d\000aUpdate [*]FROM CONTACT 'FAVORITO' = TRUE WHERE 'FAVORITO' = FALSE"; SQL statement:
SELECT * FROM CONTACT 

Update FROM CONTACT 'FAVORITO' = TRUE WHERE 'FAVORITO' = FALSE [42000-232]
2025-05-12 20:28:12.282113-03:00 jdbc[25]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 17 more
